version: '3.8'
services:
  postgres_db:
    image: postgres:15
    container_name: recharges_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recharges_db
    ports:
      - "5432:5432"